'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {Plus,Send,Trash2,Users,Pencil,RefreshCw} from 'lucide-react';
import {MobileHeader} from '@/components/app/mobile-header';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Member={user_id:string;role:'OWNER'|'ADMIN'|'MEMBER';profiles?:any};
type Workspace={id:string;name:string;is_owner:boolean;members:Member[]};
type Invite={id:string;email:string;role:string;expires_at:string;workspaces?:{name:string}};
export default function FamilyPage(){
 const[workspaces,setWorkspaces]=useState<Workspace[]>([]),[invites,setInvites]=useState<Invite[]>([]),[name,setName]=useState(''),[message,setMessage]=useState('');
 const[emails,setEmails]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{const[w,i]=await Promise.all([fetch('/api/family/workspaces',{cache:'no-store'}),fetch('/api/family/invites',{cache:'no-store'})]);setWorkspaces((await w.json()).data||[]);setInvites((await i.json()).data||[]);}catch{setMessage('Unable to load family workspaces.');}},[]);
 useEffect(()=>{load();},[load]);
 const request=async(url:string,method:string,body?:unknown)=>{const response=await fetch(url,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});if(!response.ok){const result=await response.json().catch(()=>({}));setMessage(result.error||'Action failed.');return false;}await load();return true;};
 const create=async(e:FormEvent)=>{e.preventDefault();if(await request('/api/family/workspaces','POST',{name})){setName('');setMessage('Workspace created.');}};
 const rename=async(w:Workspace)=>{const next=window.prompt('Workspace name',w.name);if(next)await request(`/api/family/workspaces/${w.id}`,'PATCH',{name:next});};
 const deleteWorkspace=async(w:Workspace)=>{if(window.confirm(`Delete ${w.name}? Shared items in it will also be deleted.`))await request(`/api/family/workspaces/${w.id}`,'DELETE');};
 return <div><MobileHeader title="Family" showBack backHref="/app/settings"/><div className="mx-auto max-w-3xl space-y-6 p-4 sm:p-6 lg:p-8"><div><h1 className="text-2xl font-bold">Family workspaces</h1><p className="text-sm text-muted-foreground">Invite family members and manage shared access.</p></div>{message&&<p className="rounded-lg bg-muted p-3 text-sm">{message}</p>}<form onSubmit={create} className="flex gap-2 rounded-xl border bg-card p-4"><Input required placeholder="Family name" value={name} onChange={e=>setName(e.target.value)}/><Button><Plus className="mr-2 h-4 w-4"/>Create</Button></form>
 {invites.length>0&&<section className="overflow-hidden rounded-xl border bg-card"><h2 className="border-b p-4 font-semibold">Pending invitations</h2><div className="divide-y">{invites.map(i=><div key={i.id} className="flex items-center gap-2 p-4"><div className="flex-1"><p className="text-sm font-medium">{i.email}</p><p className="text-xs text-muted-foreground">{i.workspaces?.name} · expires {new Date(i.expires_at).toLocaleDateString()}</p></div><Button size="icon" variant="ghost" aria-label="Resend invitation" onClick={()=>request(`/api/family/invites/${i.id}`,'POST')}><RefreshCw className="h-4 w-4"/></Button><Button size="icon" variant="ghost" aria-label="Cancel invitation" onClick={()=>request(`/api/family/invites/${i.id}`,'DELETE')}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>)}</div></section>}
 {!workspaces.length&&<div className="rounded-xl border p-8 text-center"><Users className="mx-auto h-8 w-8"/><p className="mt-2 text-sm text-muted-foreground">No family workspace yet.</p></div>}
 {workspaces.map(w=><section key={w.id} className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center border-b p-4"><div className="flex-1"><h2 className="font-semibold">{w.name}</h2><p className="text-xs text-muted-foreground">{w.members.length} members</p></div>{w.is_owner&&<><Button size="icon" variant="ghost" aria-label="Rename workspace" onClick={()=>rename(w)}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" aria-label="Delete workspace" onClick={()=>deleteWorkspace(w)}><Trash2 className="h-4 w-4 text-destructive"/></Button></>}</div>{w.is_owner&&<div className="flex gap-2 border-b p-4"><Input type="email" placeholder="family@example.com" value={emails[w.id]||''} onChange={e=>setEmails(c=>({...c,[w.id]:e.target.value}))}/><Button disabled={!emails[w.id]} onClick={()=>request('/api/family/invites','POST',{workspaceId:w.id,email:emails[w.id],role:'MEMBER'}).then(ok=>{if(ok)setEmails(c=>({...c,[w.id]:''}));})}><Send className="mr-2 h-4 w-4"/>Invite</Button></div>}<div className="divide-y">{w.members.map(m=>{const p=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;return <div key={m.user_id} className="flex items-center gap-2 p-4"><div className="flex-1"><p className="text-sm font-medium">{p?.full_name||p?.email||'Member'}</p><p className="text-xs text-muted-foreground">{p?.email}</p></div>{w.is_owner&&m.role!=='OWNER'?<><select value={m.role} onChange={e=>request(`/api/family/workspaces/${w.id}/members/${m.user_id}`,'PATCH',{role:e.target.value})} className="h-9 rounded border bg-background px-2 text-sm"><option value="MEMBER">Member</option><option value="ADMIN">Admin</option></select><Button size="sm" variant="outline" onClick={()=>request(`/api/family/workspaces/${w.id}`,'PATCH',{newOwnerId:m.user_id})}>Make owner</Button><Button size="icon" variant="ghost" onClick={()=>request(`/api/family/workspaces/${w.id}/members/${m.user_id}`,'DELETE')}><Trash2 className="h-4 w-4 text-destructive"/></Button></>:<span className="text-xs">{m.role.toLowerCase()}</span>}</div>})}</div></section>)}</div></div>;
}
