import { createAdminSupabase } from '@/lib/supabase/server';
import { GOOGLE_CALENDAR_PROVIDER, googleAccessToken, googleRequest } from '@/lib/google-calendar';

type ConflictPolicy = 'local' | 'google' | null;
function itemDate(item:any){return item.event_date||item.due_date||item.expiry_date;}
function itemTime(item:any){return item.event_time||item.due_time||item.expiry_time;}
function googleEvent(item:any,timezone:string){const date=itemDate(item),time=itemTime(item),common={summary:item.title,description:item.description||undefined,location:item.location||undefined,extendedProperties:{private:{lifeinboxItemId:item.id}}};if(time){const[h,m]=String(time).split(':').map(Number),endMinutes=h*60+m+60,endDate=new Date(`${date}T00:00:00Z`);if(endMinutes>=1440)endDate.setUTCDate(endDate.getUTCDate()+1);const endTime=`${String(Math.floor((endMinutes%1440)/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`;return{...common,start:{dateTime:`${date}T${String(time).slice(0,8)}`,timeZone:timezone},end:{dateTime:`${endDate.toISOString().slice(0,10)}T${endTime}`,timeZone:timezone}};}const next=new Date(`${date}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+1);return{...common,start:{date},end:{date:next.toISOString().slice(0,10)}};}
function eventFields(event:any){const raw=event.start?.dateTime||event.start?.date;if(!raw)return null;return{title:event.summary||'Calendar event',description:event.description||null,location:event.location||null,event_date:raw.slice(0,10),event_time:event.start?.dateTime?raw.slice(11,19):null,updated_at:new Date().toISOString()};}

export async function syncGoogleCalendar(ownerId:string,conflictPolicy:ConflictPolicy=null){
  const db=createAdminSupabase(),{token,connection}=await googleAccessToken(ownerId),calendar=encodeURIComponent(connection.calendar_id||'primary');
  const[{data:items,error:itemsError},{data:links,error:linksError},{data:profile}]=await Promise.all([
    db.from('life_items').select('id,title,description,location,due_date,event_date,expiry_date,due_time,event_time,expiry_time,status,updated_at').eq('owner_id',ownerId).is('deleted_at',null).not('status','in','(ARCHIVED,COMPLETED)'),
    db.from('calendar_sync_links').select('*').eq('owner_id',ownerId).eq('provider',GOOGLE_CALENDAR_PROVIDER),
    db.from('profiles').select('timezone').eq('id',ownerId).single(),
  ]);
  if(itemsError)throw itemsError;if(linksError)throw linksError;
  const min=new Date(),max=new Date();min.setUTCFullYear(min.getUTCFullYear()-1);max.setUTCFullYear(max.getUTCFullYear()+2);
  const query=new URLSearchParams({singleEvents:'true',showDeleted:'true',maxResults:'2500',timeMin:min.toISOString(),timeMax:max.toISOString()});
  const listing=await googleRequest(token,`/calendars/${calendar}/events?${query}`),events:any[]=listing.items||[];
  const byExternal=new Map((links||[]).map((link:any)=>[link.external_event_id,link])),byItem=new Map((links||[]).map((link:any)=>[link.life_item_id,link])),itemMap=new Map((items||[]).map((item:any)=>[item.id,item])),eventMap=new Map(events.map((event:any)=>[event.id,event]));
  let created=0,updated=0,imported=0,conflicts=0,archived=0,skipped=0;
  for(const link of links||[]){const item:any=itemMap.get(link.life_item_id),event:any=eventMap.get(link.external_event_id);if(!item||!event)continue;if(event.status==='cancelled'){await db.from('life_items').update({status:'ARCHIVED',archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',item.id);archived++;continue;}let localChanged=new Date(item.updated_at)>new Date(link.last_synced_at),remoteChanged=new Date(event.updated)>new Date(link.last_synced_at);if(localChanged&&remoteChanged&&!conflictPolicy){conflicts++;continue;}if(localChanged&&remoteChanged&&conflictPolicy==='local')remoteChanged=false;if(localChanged&&remoteChanged&&conflictPolicy==='google')localChanged=false;if(remoteChanged){const fields=eventFields(event);if(fields)await db.from('life_items').update(fields).eq('id',item.id);await db.from('calendar_sync_links').update({external_etag:event.etag,last_synced_at:new Date().toISOString()}).eq('id',link.id);updated++;}else if(localChanged){const changed=await googleRequest(token,`/calendars/${calendar}/events/${encodeURIComponent(event.id)}`,{method:'PATCH',body:JSON.stringify(googleEvent(item,profile?.timezone||'UTC'))});await db.from('calendar_sync_links').update({external_etag:changed.etag,last_synced_at:new Date().toISOString()}).eq('id',link.id);updated++;}else skipped++;}
  for(const item of items||[]){if(!itemDate(item)||byItem.has(item.id))continue;const event=await googleRequest(token,`/calendars/${calendar}/events`,{method:'POST',body:JSON.stringify(googleEvent(item,profile?.timezone||'UTC'))});await db.from('calendar_sync_links').insert({owner_id:ownerId,life_item_id:item.id,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});created++;}
  for(const event of events){if(event.status==='cancelled'||byExternal.has(event.id))continue;const fields=eventFields(event);if(!fields)continue;const known=event.extendedProperties?.private?.lifeinboxItemId;if(known&&itemMap.has(known)){await db.from('calendar_sync_links').insert({owner_id:ownerId,life_item_id:known,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});continue;}const{data:newItem,error}=await db.from('life_items').insert({owner_id:ownerId,category:'GENERAL_REMINDER',status:'UPCOMING',currency:'LKR',recurring:false,ai_generated:false,ai_confidence:1,confirmed:true,...fields}).select('id').single();if(error)throw error;await db.from('calendar_sync_links').insert({owner_id:ownerId,life_item_id:newItem.id,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});imported++;}
  await db.from('integration_connections').update({updated_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('provider',GOOGLE_CALENDAR_PROVIDER);
  return{ok:true,created,updated,imported,archived,conflicts,skipped};
}
