import { execFile } from 'node:child_process';
import { mkdtemp, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const options={windowsHide:true,timeout:120_000,maxBuffer:5*1024*1024};
async function run(executable:string,args:string[]){return (await execFileAsync(executable,args,options)).stdout.trim();}
export async function extractLocalText(bytes:Uint8Array,mimeType:string){const dir=await mkdtemp(path.join(tmpdir(),'lifeinbox-ocr-'));const isPdf=mimeType==='application/pdf',input=path.join(dir,isPdf?'input.pdf':'input.img');try{await writeFile(input,bytes);const tesseract=process.env.TESSERACT_PATH||'C:\\Program Files\\Tesseract-OCR\\tesseract.exe';if(!isPdf)return run(tesseract,[input,'stdout','-l','eng']);const pdftotext=process.env.PDFTOTEXT_PATH||'pdftotext.exe',pdftoppm=process.env.PDFTOPPM_PATH||'pdftoppm.exe';try{const embedded=await run(pdftotext,['-layout',input,'-']);if(embedded.length>20)return embedded;}catch{}const prefix=path.join(dir,'page');await run(pdftoppm,['-f','1','-l','5','-r','200','-png',input,prefix]);const pages=(await readdir(dir)).filter(name=>/^page-.*\.png$/i.test(name)).sort();const output:string[]=[];for(const page of pages)output.push(await run(tesseract,[path.join(dir,page),'stdout','-l','eng']));return output.join('\n\n').trim();}finally{await rm(dir,{recursive:true,force:true});}}
export function fallbackExtraction(text:string){const clean=text.replace(/\r/g,'').trim(),first=clean.split('\n').map(v=>v.trim()).find(Boolean)||'Scanned document';return{title:first.slice(0,160),category:'GENERAL_REMINDER',description:clean.slice(0,10000)||null,organization:null,person_name:null,amount:null,currency:'LKR',issue_date:null,due_date:null,event_date:null,expiry_date:null,reference_number:null,location:null,action_required:'Review the locally extracted text',confidence:0.35,field_confidence:{title:0.35,description:0.5},suggested_reminders:[]};}
