import type {
  LifeItem,
  LifeItemCategory,
  LifeItemStatus,
  Notification,
  User,
  UserPreference,
} from './types';

export const mockUser: User = {
  id: 'user-1',
  fullName: 'Sarah Perera',
  email: 'sarah@example.com',
  image: null,
  country: 'Sri Lanka',
  timezone: 'Asia/Colombo',
  createdAt: '2026-01-15T08:00:00Z',
  lastLoginAt: '2026-09-22T06:30:00Z',
};

export const mockUserPreference: UserPreference = {
  pushEnabled: true,
  emailEnabled: true,
  morningSummary: true,
  weeklySummary: false,
  defaultNotificationTime: '08:00',
  timezone: 'Asia/Colombo',
};

export const mockLifeItems: LifeItem[] = [
  {
    id: 'li-1',
    title: 'CEB Electricity Bill',
    category: 'BILL' as LifeItemCategory,
    description: 'Monthly electricity bill from Ceylon Electricity Board',
    organization: 'Ceylon Electricity Board',
    personName: null,
    amount: 8450,
    currency: 'LKR',
    issueDate: '2026-09-20',
    dueDate: '2026-09-28',
    eventDate: null,
    expiryDate: null,
    referenceNumber: '12345678',
    location: null,
    actionRequired: 'Pay electricity bill',
    status: 'NEEDS_ATTENTION' as LifeItemStatus,
    recurring: true,
    recurrenceRule: 'MONTHLY',
    aiGenerated: true,
    aiConfidence: 0.95,
    confirmed: true,
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:05:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [
      {
        id: 'att-1',
        lifeItemId: 'li-1',
        fileName: 'ceb-bill-sep-2026.png',
        fileType: 'IMAGE',
        mimeType: 'image/png',
        fileSize: 245000,
        createdAt: '2026-09-20T10:00:00Z',
      },
    ],
    reminders: [
      {
        id: 'rem-1',
        lifeItemId: 'li-1',
        remindAt: '2026-09-25T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-2',
        lifeItemId: 'li-1',
        remindAt: '2026-09-28T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-2',
    title: 'Netflix Subscription',
    category: 'SUBSCRIPTION' as LifeItemCategory,
    description: 'Monthly Netflix subscription renewal',
    organization: 'Netflix',
    personName: null,
    amount: 2990,
    currency: 'LKR',
    issueDate: null,
    dueDate: '2026-10-18',
    eventDate: null,
    expiryDate: null,
    referenceNumber: null,
    location: null,
    actionRequired: 'Review subscription',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: true,
    recurrenceRule: 'MONTHLY',
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-08-18T12:00:00Z',
    updatedAt: '2026-08-18T12:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-3',
        lifeItemId: 'li-2',
        remindAt: '2026-10-15T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-3',
    title: 'Emirates EK649',
    category: 'TRAVEL' as LifeItemCategory,
    description: 'Flight from Colombo to Dubai',
    organization: 'Emirates',
    personName: null,
    amount: null,
    currency: 'LKR',
    issueDate: null,
    dueDate: null,
    eventDate: '2026-10-04',
    expiryDate: null,
    referenceNumber: 'EK649',
    location: 'CMB → DXB',
    actionRequired: 'Check in 24 hours before departure',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: false,
    recurrenceRule: null,
    aiGenerated: true,
    aiConfidence: 0.92,
    confirmed: true,
    createdAt: '2026-09-15T14:00:00Z',
    updatedAt: '2026-09-15T14:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [
      {
        id: 'att-2',
        lifeItemId: 'li-3',
        fileName: 'emirates-ek649.pdf',
        fileType: 'PDF',
        mimeType: 'application/pdf',
        fileSize: 512000,
        createdAt: '2026-09-15T14:00:00Z',
      },
    ],
    reminders: [
      {
        id: 'rem-4',
        lifeItemId: 'li-3',
        remindAt: '2026-10-03T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-5',
        lifeItemId: 'li-3',
        remindAt: '2026-10-04T04:25:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-4',
    title: 'Dental Appointment',
    category: 'APPOINTMENT' as LifeItemCategory,
    description: 'Regular dental check-up and cleaning',
    organization: 'Smile Dental Clinic',
    personName: 'Dr. Perera',
    amount: 3500,
    currency: 'LKR',
    issueDate: null,
    dueDate: null,
    eventDate: '2026-09-29',
    expiryDate: null,
    referenceNumber: null,
    location: 'Smile Dental Clinic, Colombo 03',
    actionRequired: 'Attend appointment',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: false,
    recurrenceRule: null,
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-6',
        lifeItemId: 'li-4',
        remindAt: '2026-09-28T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-7',
        lifeItemId: 'li-4',
        remindAt: '2026-09-29T13:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-5',
    title: 'Vehicle Insurance',
    category: 'INSURANCE' as LifeItemCategory,
    description: 'Annual vehicle insurance renewal',
    organization: 'Sri Lanka Insurance',
    personName: null,
    amount: 89000,
    currency: 'LKR',
    issueDate: null,
    dueDate: null,
    eventDate: null,
    expiryDate: '2026-12-15',
    referenceNumber: 'SLI-2025-78945',
    location: null,
    actionRequired: 'Renew vehicle insurance',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: true,
    recurrenceRule: 'YEARLY',
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2025-12-15T10:00:00Z',
    updatedAt: '2025-12-15T10:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-8',
        lifeItemId: 'li-5',
        remindAt: '2026-11-15T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-9',
        lifeItemId: 'li-5',
        remindAt: '2026-12-08T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-10',
        lifeItemId: 'li-5',
        remindAt: '2026-12-14T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-6',
    title: 'MacBook Warranty',
    category: 'WARRANTY' as LifeItemCategory,
    description: 'Apple MacBook Pro 1-year warranty',
    organization: 'Apple',
    personName: null,
    amount: null,
    currency: 'LKR',
    issueDate: null,
    dueDate: null,
    eventDate: null,
    expiryDate: '2027-09-12',
    referenceNumber: 'APP-WAR-2026-456',
    location: null,
    actionRequired: null,
    status: 'UPCOMING' as LifeItemStatus,
    recurring: false,
    recurrenceRule: null,
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-11',
        lifeItemId: 'li-6',
        remindAt: '2027-08-13T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-12',
        lifeItemId: 'li-6',
        remindAt: '2027-09-05T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-7',
    title: 'Dialog Mobile Bill',
    category: 'BILL' as LifeItemCategory,
    description: 'Monthly mobile phone bill',
    organization: 'Dialog',
    personName: null,
    amount: 1850,
    currency: 'LKR',
    issueDate: '2026-09-18',
    dueDate: '2026-09-22',
    eventDate: null,
    expiryDate: null,
    referenceNumber: 'DIALOG-99201',
    location: null,
    actionRequired: 'Pay mobile bill',
    status: 'DUE_TODAY' as LifeItemStatus,
    recurring: true,
    recurrenceRule: 'MONTHLY',
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-13',
        lifeItemId: 'li-7',
        remindAt: '2026-09-19T08:00:00Z',
        channel: 'BOTH',
        status: 'SENT',
        sentAt: '2026-09-19T08:00:00Z',
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-8',
    title: 'Amazon Return',
    category: 'RETURN' as LifeItemCategory,
    description: 'Return wireless earbuds',
    organization: 'Amazon',
    personName: null,
    amount: null,
    currency: 'USD',
    issueDate: null,
    dueDate: '2026-09-30',
    eventDate: null,
    expiryDate: null,
    referenceNumber: 'AMZ-RET-55821',
    location: null,
    actionRequired: 'Ship return package',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: false,
    recurrenceRule: null,
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-09-20T15:00:00Z',
    updatedAt: '2026-09-20T15:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-14',
        lifeItemId: 'li-8',
        remindAt: '2026-09-27T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-15',
        lifeItemId: 'li-8',
        remindAt: '2026-09-29T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-9',
    title: 'Passport Renewal',
    category: 'DOCUMENT_EXPIRY' as LifeItemCategory,
    description: 'Sri Lankan passport expiry',
    organization: 'Department of Immigration',
    personName: null,
    amount: null,
    currency: 'LKR',
    issueDate: null,
    dueDate: null,
    eventDate: null,
    expiryDate: '2027-03-10',
    referenceNumber: 'SL-PP-789456',
    location: null,
    actionRequired: 'Renew passport',
    status: 'UPCOMING' as LifeItemStatus,
    recurring: false,
    recurrenceRule: null,
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
    completedAt: null,
    archivedAt: null,
    attachments: [],
    reminders: [
      {
        id: 'rem-16',
        lifeItemId: 'li-9',
        remindAt: '2026-09-10T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
      {
        id: 'rem-17',
        lifeItemId: 'li-9',
        remindAt: '2026-12-10T08:00:00Z',
        channel: 'BOTH',
        status: 'PENDING',
        sentAt: null,
        failedAt: null,
      },
    ],
  },
  {
    id: 'li-10',
    title: 'Water Bill — NWSDB',
    category: 'BILL' as LifeItemCategory,
    description: 'Monthly water bill',
    organization: 'National Water Supply & Drainage Board',
    personName: null,
    amount: 1200,
    currency: 'LKR',
    issueDate: '2026-08-15',
    dueDate: '2026-08-30',
    eventDate: null,
    expiryDate: null,
    referenceNumber: 'NWSDB-44521',
    location: null,
    actionRequired: 'Pay water bill',
    status: 'COMPLETED' as LifeItemStatus,
    recurring: true,
    recurrenceRule: 'MONTHLY',
    aiGenerated: false,
    aiConfidence: 1,
    confirmed: true,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-30T14:00:00Z',
    completedAt: '2026-08-30T14:00:00Z',
    archivedAt: null,
    attachments: [],
    reminders: [],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    lifeItemId: 'li-7',
    title: 'Dialog Mobile Bill Due Today',
    message: 'Your Dialog mobile bill of LKR 1,850 is due today.',
    type: 'REMINDER',
    read: false,
    createdAt: '2026-09-22T08:00:00Z',
  },
  {
    id: 'notif-2',
    lifeItemId: 'li-1',
    title: 'CEB Bill Due in 3 Days',
    message: 'Your CEB electricity bill of LKR 8,450 is due on 28 September.',
    type: 'REMINDER',
    read: false,
    createdAt: '2026-09-22T08:00:00Z',
  },
  {
    id: 'notif-3',
    lifeItemId: 'li-4',
    title: 'Dental Appointment Tomorrow',
    message: 'You have a dental appointment tomorrow at 3:00 PM at Smile Dental Clinic.',
    type: 'REMINDER',
    read: false,
    createdAt: '2026-09-22T08:00:00Z',
  },
  {
    id: 'notif-4',
    lifeItemId: null,
    title: 'Welcome to LifeInbox',
    message: 'Your account is all set up. Start by remembering something!',
    type: 'SYSTEM',
    read: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
];
