'use client';

import { useEffect, useState } from 'react';
import { CalendarDays, Loader2, RefreshCw, Unplug } from 'lucide-react';
import { MobileHeader } from '@/components/app/mobile-header';
import { Button } from '@/components/ui/button';

export default function IntegrationsPage() {
  const [connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[conflicts,setConflicts]=useState(0);
  const load=async()=>{setLoading(true);const response=await fetch('/api/integrations/google/status',{cache:'no-store'});const result=await response.json();setConnected(Boolean(result.connected));setLoading(false);};
  useEffect(()=>{load();const result=new URLSearchParams(window.location.search).get('google');if(result==='connected')setMessage('Google Calendar connected successfully.');else if(result)setMessage('Google Calendar connection failed. Please try again.');},[]);
  const sync=async(conflictPolicy?:'local'|'google')=>{setWorking(true);setMessage('');const response=await fetch('/api/integrations/google/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conflictPolicy})});const result=await response.json();setConflicts(result.conflicts||0);setMessage(response.ok?`Sync complete: ${result.created} exported, ${result.imported} imported, ${result.updated} updated, ${result.conflicts} conflict(s).`:(result.error||'Calendar sync failed.'));setWorking(false);};
  const disconnect=async()=>{if(!confirm('Disconnect Google Calendar? Existing Google events will remain.'))return;setWorking(true);const response=await fetch('/api/integrations/google/status',{method:'DELETE'});if(response.ok){setConnected(false);setMessage('Google Calendar disconnected.');}else setMessage('Unable to disconnect Google Calendar.');setWorking(false);};
  return <div><MobileHeader title="Connected apps" showBack backHref="/app/settings"/><div className="mx-auto max-w-2xl space-y-6 p-4 sm:p-6 lg:p-8"><div><h1 className="text-2xl font-bold">Connected apps</h1><p className="mt-1 text-sm text-muted-foreground">Connect your calendar and keep dated LifeInbox items synchronized.</p></div>{message&&<p className="rounded-lg border bg-card p-3 text-sm">{message}</p>}{conflicts>0&&<div className="rounded-lg border border-warning/40 bg-warning/10 p-4"><p className="text-sm font-medium">Choose how to resolve {conflicts} calendar conflict(s).</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>sync('local')} disabled={working}>Keep LifeInbox</Button><Button size="sm" variant="outline" onClick={()=>sync('google')} disabled={working}>Keep Google</Button></div></div>}<section className="rounded-xl border bg-card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary/10 text-primary"><CalendarDays className="h-5 w-5"/></div><div className="flex-1"><h2 className="font-semibold">Google Calendar</h2><p className="text-sm text-muted-foreground">{loading?'Checking connection...':connected?'Connected - two-way manual sync is ready.':'Not connected'}</p></div>{loading?<Loader2 className="h-5 w-5 animate-spin"/>:connected?<div className="flex gap-2"><Button onClick={()=>sync()} disabled={working}>{working?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Sync now</Button><Button variant="outline" onClick={disconnect} disabled={working}><Unplug className="mr-2 h-4 w-4"/>Disconnect</Button></div>:<Button asChild><a href="/api/integrations/google/connect">Connect Google Calendar</a></Button>}</div><p className="mt-4 text-xs text-muted-foreground">Sync imports Google events and exports active LifeInbox items. If both copies changed, choose which version to keep.</p></section></div></div>;
}
