import { NextResponse } from 'next/server';
import { requireUser, createAdminSupabase } from '@/lib/supabase/server';
import { GOOGLE_CALENDAR_PROVIDER, googleAccessToken, googleRequest } from '@/lib/google-calendar';
import { apiError } from '@/lib/http';
export const runtime='nodejs';
function itemDate(i:any){return i.event_date||i.due_date||i.expiry_date;} function itemTime(i:any){return i.event_time||i.due_time||i.expiry_time;}
function googleEvent(i:any,tz:string){const date=itemDate(i),time=itemTime(i),common={summary:i.title,description:i.description||undefined,location:i.location||undefined,extendedProperties:{private:{lifeinboxItemId:i.id}}};if(time)return{...common,start:{dateTime:`${date}T${String(time).slice(0,8)}`,timeZone:tz},end:{dateTime:`${date}T${String(time).slice(0,8)}`,timeZone:tz}};const next=new Date(`${date}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+1);return{...common,start:{date},end:{date:next.toISOString().slice(0,10)}};}
function eventFields(e:any){const raw=e.start?.dateTime||e.start?.date;if(!raw)return null;return{title:e.summary||'Calendar event',description:e.description||null,location:e.location||null,event_date:raw.slice(0,10),event_time:e.start?.dateTime?raw.slice(11,19):null,updated_at:new Date().toISOString()};}
export async function POST(){try{const{user}=await requireUser(),db=createAdminSupabase(),{token,connection}=await googleAccessToken(user.id),calendar=encodeURIComponent(connection.calendar_id||'primary');const[{data:items,error:ie},{data:links,error:le},{data:profile}]=await Promise.all([db.from('life_items').select('id,title,description,location,due_date,event_date,expiry_date,due_time,event_time,expiry_time,status,updated_at').eq('owner_id',user.id).is('deleted_at',null).not('status','in','(ARCHIVED,COMPLETED)'),db.from('calendar_sync_links').select('*').eq('owner_id',user.id).eq('provider',GOOGLE_CALENDAR_PROVIDER),db.from('profiles').select('timezone').eq('id',user.id).single()]);if(ie)throw ie;if(le)throw le;const min=new Date(),max=new Date();min.setUTCFullYear(min.getUTCFullYear()-1);max.setUTCFullYear(max.getUTCFullYear()+2);const q=new URLSearchParams({singleEvents:'true',showDeleted:'true',maxResults:'2500',timeMin:min.toISOString(),timeMax:max.toISOString()}),listing=await googleRequest(token,`/calendars/${calendar}/events?${q}`),events:any[]=listing.items||[],byExternal=new Map((links||[]).map((l:any)=>[l.external_event_id,l])),byItem=new Map((links||[]).map((l:any)=>[l.life_item_id,l])),itemMap=new Map((items||[]).map((i:any)=>[i.id,i])),eventMap=new Map(events.map((e:any)=>[e.id,e]));let created=0,updated=0,imported=0,conflicts=0,archived=0,skipped=0;
for(const link of links||[]){const item:any=itemMap.get(link.life_item_id),event:any=eventMap.get(link.external_event_id);if(!item||!event)continue;if(event.status==='cancelled'){await db.from('life_items').update({status:'ARCHIVED',archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',item.id);archived++;continue;}const lc=new Date(item.updated_at)>new Date(link.last_synced_at),rc=new Date(event.updated)>new Date(link.last_synced_at);if(lc&&rc){conflicts++;continue;}if(rc){const fields=eventFields(event);if(fields)await db.from('life_items').update(fields).eq('id',item.id);await db.from('calendar_sync_links').update({external_etag:event.etag,last_synced_at:new Date().toISOString()}).eq('id',link.id);updated++;}else if(lc){const changed=await googleRequest(token,`/calendars/${calendar}/events/${encodeURIComponent(event.id)}`,{method:'PATCH',body:JSON.stringify(googleEvent(item,profile?.timezone||'UTC'))});await db.from('calendar_sync_links').update({external_etag:changed.etag,last_synced_at:new Date().toISOString()}).eq('id',link.id);updated++;}else skipped++;}
for(const item of items||[]){if(!itemDate(item)||byItem.has(item.id))continue;const event=await googleRequest(token,`/calendars/${calendar}/events`,{method:'POST',body:JSON.stringify(googleEvent(item,profile?.timezone||'UTC'))});await db.from('calendar_sync_links').insert({owner_id:user.id,life_item_id:item.id,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});created++;}
for(const event of events){if(event.status==='cancelled'||byExternal.has(event.id))continue;const fields=eventFields(event);if(!fields)continue;const known=event.extendedProperties?.private?.lifeinboxItemId;if(known&&itemMap.has(known)){await db.from('calendar_sync_links').insert({owner_id:user.id,life_item_id:known,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});continue;}const{data:newItem,error}=await db.from('life_items').insert({owner_id:user.id,category:'GENERAL_REMINDER',status:'UPCOMING',currency:'LKR',recurring:false,ai_generated:false,ai_confidence:1,confirmed:true,...fields}).select('id').single();if(error)throw error;await db.from('calendar_sync_links').insert({owner_id:user.id,life_item_id:newItem.id,provider:GOOGLE_CALENDAR_PROVIDER,external_event_id:event.id,external_etag:event.etag,last_synced_at:new Date().toISOString()});imported++;}
await db.from('integration_connections').update({updated_at:new Date().toISOString()}).eq('owner_id',user.id).eq('provider',GOOGLE_CALENDAR_PROVIDER);return NextResponse.json({ok:true,created,updated,imported,archived,conflicts,skipped});}catch(error){return apiError(error);}}
