import { NextRequest,NextResponse } from 'next/server';
import { z } from 'zod';
import { requireUser,createAdminSupabase } from '@/lib/supabase/server';
import { apiError } from '@/lib/http';
import { writeAudit } from '@/lib/audit';

const patchSchema=z.object({name:z.string().trim().min(1).max(100).optional(),newOwnerId:z.string().uuid().optional()}).refine((value)=>value.name||value.newOwnerId);
export async function PATCH(request:NextRequest,{params}:{params:{id:string}}){try{const{user}=await requireUser();const db=createAdminSupabase();const{data:workspace}=await db.from('workspaces').select('*').eq('id',params.id).eq('owner_id',user.id).single();if(!workspace)throw new Error('NOT_FOUND');const input=patchSchema.parse(await request.json());if(input.newOwnerId){const{data:member}=await db.from('workspace_members').select('user_id').eq('workspace_id',params.id).eq('user_id',input.newOwnerId).single();if(!member)throw new Error('NOT_FOUND');await db.from('workspaces').update({owner_id:input.newOwnerId,...(input.name?{name:input.name}:{})}).eq('id',params.id);await db.from('workspace_members').update({role:'ADMIN'}).eq('workspace_id',params.id).eq('user_id',user.id);await db.from('workspace_members').update({role:'OWNER'}).eq('workspace_id',params.id).eq('user_id',input.newOwnerId);}else await db.from('workspaces').update({name:input.name}).eq('id',params.id);await writeAudit(db,user.id,input.newOwnerId?'TRANSFER_WORKSPACE':'RENAME_WORKSPACE','workspace',params.id,input);return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
export async function DELETE(_:NextRequest,{params}:{params:{id:string}}){try{const{user}=await requireUser();const db=createAdminSupabase();const{error}=await db.from('workspaces').delete().eq('id',params.id).eq('owner_id',user.id);if(error)throw error;await writeAudit(db,user.id,'DELETE_WORKSPACE','workspace',params.id);return new NextResponse(null,{status:204});}catch(error){return apiError(error);}}
